/**
 * ============================================================
 *  TaskModel.js  ·  Mongoose Schema & Model Definition
 * ============================================================
 *
 *  In a real MERN project this file lives at:
 *    server/models/TaskModel.js
 *
 *  It uses Mongoose to define the shape of a Task document
 *  in MongoDB.  Every field, its type, default value, and
 *  validation rule is declared here — keeping the data layer
 *  completely separated from the route / controller layer.
 *
 *  Interview talking points:
 *    • Mongoose schema vs MongoDB collection
 *    • Built-in validators (required, minlength, enum)
 *    • timestamps option auto-adds createdAt / updatedAt
 *    • The model wraps the schema and provides CRUD methods
 *    • We export the compiled model so controllers can import it
 * ============================================================
 */

// const mongoose = require("mongoose");      // ← real Node.js import

// ─────────────────────────────────────────────
//  Schema Definition
// ─────────────────────────────────────────────
const taskSchema = {
  /*
   *  In real Mongoose code this would be:
   *
   *  const taskSchema = new mongoose.Schema({ ... }, { timestamps: true });
   *
   *  The object below documents every field exactly as it would
   *  appear in the Mongoose schema so you can explain it in an
   *  interview line-by-line.
   */

  /** Unique identifier — MongoDB auto-generates _id (ObjectId) */
  _id: "ObjectId (auto-generated by MongoDB)",

  /** Task title — required, trimmed, max 150 characters */
  title: {
    type: "String",
    required: [true, "Task title is required"],
    trim: true,
    maxlength: [150, "Title cannot exceed 150 characters"],
  },

  /** Optional longer description */
  description: {
    type: "String",
    trim: true,
    default: "",
  },

  /** Whether the task has been completed */
  completed: {
    type: "Boolean",
    default: false,
  },

  /**
   *  Priority level using an enum to restrict allowed values.
   *  Mongoose will throw a ValidationError if anything other
   *  than these three strings is supplied.
   */
  priority: {
    type: "String",
    enum: ["low", "medium", "high"],
    default: "medium",
  },

  /**
   *  Category tag — helps group tasks visually in the UI.
   *  enum keeps data consistent across documents.
   */
  category: {
    type: "String",
    enum: ["work", "personal", "health", "learning", "finance", "other"],
    default: "personal",
  },

  /** Due date — stored as a Date; optional */
  dueDate: {
    type: "Date",
    default: null,
  },

  // createdAt & updatedAt are added automatically by
  // { timestamps: true } in the real Mongoose schema options
};

/**
 *  Real Mongoose model compilation (commented out for the
 *  browser-based demo — uncomment in the actual Node.js server):
 *
 *  const Task = mongoose.model("Task", taskSchema);
 *  module.exports = Task;
 */

// Export the schema definition for documentation purposes
export default taskSchema;
